### ISSUE TITLE
Search broken when using url bar / search bar (72.0.1)

### ISSUE THREAD

**Issue by iamthekings5** [muckSponge/MaterialFox#201]
**Sanity checks (must complete)**
- [/] I have read and followed the installation instructions in the README
- [/] I have not modified the userChrome.css file
- [/] I have tested the latest release or commit on master

**Describe the bug**
It seems the text is being clipped off.
![image](https://user-images.githubusercontent.com/58262947/72014799-851cf600-3258-11ea-904e-52b7454c0dc8.png)

**To Reproduce**
Type anything into search bar on 72.0.1

**System info**
 - OS: Windows 10

**Comment by fmeyertoens** [comment]
Duplicate of #198

**Comment by D3faIt** [comment]
@fmeyertoens 

How is this a duplicate?
Well sure, the `Search with ...` text appears too close to search suggestions.. but what about all the other stuff?

**Comment by fmeyertoens** [comment]
If you look at the comments of the other issue you can see almost exactly the same screenshot as in this issue + MuckSponge replied that they rearranged the DOM and he is working on a fix.
I don't see anything new here except maybe a more generic title.

**Comment by iamthekings5** [comment]
I'd leave it. The other issue is separate from the one here, and while there was some discussion / a possible fix coming, this thread being made isn't really a duplicate issue because the issue is not listed to begin with. Thanks for pointing out that a fix is coming though.

**Comment by muckSponge** [comment]
I've probably missed a few edge cases but give e3cb6ca274e15c89b865dc0ad7977b164f492611 a try. It's a new branch for 72 (now set as the default).

**Comment by iamthekings5** [comment]
I can't recall exactly, but prior to 72 was 'Search with Google' supposed to appear so many times? Thanks for your work.

![image](https://user-images.githubusercontent.com/58262947/72206855-6bfb8b80-348a-11ea-8dbb-53fe9a1a0a52.png)

**Comment by fmeyertoens** [comment]
No, it should only appear on hover or selected (via keyboard/active?).

**Comment by 3YH** [comment]
It is fixed for me with https://github.com/muckSponge/MaterialFox/commit/e3cb6ca274e15c89b865dc0ad7977b164f492611.

**Comment by muckSponge** [comment]
> I can't recall exactly, but prior to 72 was 'Search with Google' supposed to appear so many times? Thanks for your work.
> 
> ![image](https://user-images.githubusercontent.com/58262947/72206855-6bfb8b80-348a-11ea-8dbb-53fe9a1a0a52.png)

Ahahah ok that's a bit excessive. Still some work to do it seems. Trying to make it as Chromehlike as possible but many edge cases.

**Comment by muckSponge** [comment]
Should be much more consistent with Chrome now. "Search with Google" action only appears once for the first item. A few other tweaks here and there to keep everything consistent, including action and url `font-size` and `color`, and icon `fill-opacity`.

**Comment by muckSponge** [comment]
Yep, that's intended. This is how Chrome does it:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5405629/72254911-82a40d00-3659-11ea-9da4-c2693d03bd27.png">
If there's a visible urlbar action (e.g. "Switch to tab") _and_ URL is shown, the URL is placed on a second row. Unfortunately, Firefox doesn't provide an action button; only the text, but if it were all on the same row it would look more cluttered and may be more difficult to read.

**Comment by iamthekings5** [comment]
Since the issue has been resolved, I'll be marking this as close. Thanks for your work!

**Comment by edoz90** [comment]
Hi all,

on Firefox 72.0.1 (64-bit) on ArchLinux the issue is not fixed.

![ma](https://user-images.githubusercontent.com/6991986/72468862-6da4b680-37de-11ea-9578-941744c23273.png)
Let me know if you need more information/screenshoots

**Comment by edoz90** [comment]
Hi,

> @edoz90 can you check you're using branch 72 and not master?
oh f**k, sorry I'm dumb; I was on the master branch....

Using the 72 branch:

![image](https://user-images.githubusercontent.com/6991986/72521621-0fb6b400-385c-11ea-9318-ffff8c418cc3.png)

**Comment by Aire-One** [comment]
Strangely enough, I don't have these glitch...

![2020-01-16-123943_1348x728_scrot](https://user-images.githubusercontent.com/6602958/72522163-4d680c80-385d-11ea-804c-a2c153043d80.png)

**Comment by muckSponge** [comment]
@Aire-One, looks like there's a margin or padding issue on the background highlight and the settings button (bottom right) is too far to the right.

@edoz90, there's still a problem here. Seems like the contents of each result item are vertically offset by about 12px, which is rather strange.

**Comment by Aire-One** [comment]
@muckSponge because I run nightly I didn't open issues for this...

The urlbar/megabar is also slightly shifted to the bottom since a few versions when they changed it. But users from stable firefox report there is no issue, so I guess it's a nightly thing and I didn't reported it here to not make your work harder by supporting nightly for apparently only 1 user: me.

**Comment by muckSponge** [comment]
Ah, fair enough. Beta is about where I draw the line at the moment in terms of fixing bugs because I at least know it's going to carry through to stable. Looks like I'll probably have a fair amount of fixing to do in the future.

**Comment by muckSponge** [comment]
I'm closing this due to inactivity but will reopen if that 12px offset issue persists.

**Comment by edoz90** [comment]
Hi!

I don't know if this can be marked as fixed. I've 73.0 and on branch 72 the result is:
![image](https://user-images.githubusercontent.com/6991986/74545417-22023b80-4f49-11ea-9482-1214ec64e66b.png)

on branch 74:
![image](https://user-images.githubusercontent.com/6991986/74545438-29c1e000-4f49-11ea-9a6a-c22784a06ee8.png)

**Comment by muckSponge** [comment]
I'll reopen this but still not able to reproduce. Does it occur with a fresh profile?

**Comment by notdodo** [comment]
![Screenshot_20200404_105252](https://user-images.githubusercontent.com/6991986/78422846-aa0be400-7662-11ea-8216-b30cda893324.png)

With the latest updates (both firefox and materialfox) the issue is not present.
I think we can close this
