### ISSUE TITLE
Style of autofill is broken

### ISSUE THREAD

**Issue by heubergen** [muckSponge/MaterialFox#61]
<img width="253" alt="image001" src="https://user-images.githubusercontent.com/5529410/51850885-feab2500-2322-11e9-8d5e-32eb1b900465.png">

I think no more words are needed.

BTW: Keep up with the great work, my Fox looks better with every commit!

**Comment by muckSponge** [comment]
It seems this kind of `richlistbox` has a forced height so if I try to style it like all the other popup menus it always overflows due to the different heights. Will experiment a bit more but it doesn't look promising - means we might not be able to get that rounded border.

**Comment by heubergen** [comment]
Now it's bigger but the issue is not fixed yet.
<img width="274" alt="image001" src="https://user-images.githubusercontent.com/5529410/51917358-ad14a000-23df-11e9-82c2-be4b2cfe747c.png">

I tested it with this page 
https://hongkiat.github.io/html5-loginpage/

**Comment by muckSponge** [comment]
Try latest commit, should be fixed.

**Comment by heubergen** [comment]
No, still not. With MaterialFox:
<img width="178" alt="screen shot 2019-01-29 at 16 56 04" src="https://user-images.githubusercontent.com/5529410/51920999-cb31ce80-23e6-11e9-993b-260de0b877c4.png">
Firefox Vanilla:<img width="177" alt="screen shot 2019-01-29 at 16 56 07" src="https://user-images.githubusercontent.com/5529410/51921000-cb31ce80-23e6-11e9-92c5-ab3c7be5d52f.png">

The space between the key symbol and the left border is still to big.

**Comment by muckSponge** [comment]
From what I can see it's the exact same style as most other kinds of popups, menus, and dropdowns now. Anything else would be inconsistent. Note that the padding on the left of the icon should be the same as the padding to the right of the label. In vanilla Firefox this just happens to be a much smaller amount on both sides, making it look excessive in comparison. I'd argue that vanilla looks a) worse, and b) inconsistent with their own dropdowns and menus.

**Comment by heubergen** [comment]
Okay I see it now, so let's close this issue. We don't need to discuss design here :)
